# .github/workflows/deploy.yml

name: Deploy to ECS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key and known hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SPARKAI_WEB_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SPARKAI_WEB_KNOWN_HOSTS }}

      - name: Deploy to ECS Server
        run: |
          ssh root@47.117.144.223 <<EOF
            echo "Navigate to project directory"
            cd ~/liao/cicd_test/sparkai_web/

            echo "Pull latest code from GitHub"
            git pull origin main

            echo "Install dependencies"
            pnpm install

            echo "Build sparkai_web"
            pnpm build

            echo "Restart sparkai_web"
            pm2 restart sparkai_web

            echo "Deployment completed sparkai_web successfully"
          EOF